name: tictactoe_arc
description: A TicTacToe game with Arc blockchain integration (testnet first).
publish_to: "none"
version: 0.0.1
environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.32.0
  firebase_auth: ^4.6.0
  firebase_database: ^10.0.0
  http: ^0.13.6
  web3dart: ^2.5.0
  walletconnect_dart: ^0.0.11
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
